#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           :                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://play.google.com/store/apps/details?id=com.kirin.wallpaper                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                            # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : WallpaperVerse                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Discover a universe of stunning wallpapers tailored to your style with WallpaperVerse.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Kirin Studio                                
your_link                                 :            
your_city                                 : Copenhagen                                
email_address                             : 1067300893@qq.com
facebook_username                         :                                           
instagram_username                        :  
twitter_username                          :   
github_username                           : 
youtube_username                          :
mastodon_link                             :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Rich Image Categories
    description                           : Discover Diverse Collections, Explore a wide array of image categories, offering an extensive range of wallpapers for every taste and style.
    fontawesome_icon_name                 : rocket
    
  - title                                 : Latest Images
    description                           : Stay Updated, Access the freshest wallpapers regularly updated to keep your device looking sleek and modern.
    fontawesome_icon_name                 : user-shield

  - title                                 : Convenient Search Functionality
    description                           : Effortless Exploration, Seamlessly search for wallpapers using our user-friendly and efficient search feature, ensuring you find the perfect wallpaper in no time.
    fontawesome_icon_name                 : mug-hot

  
  - title                                 : Wallpaper Management
    description                           : Collect, Save, and Set, Save your favorite wallpapers, collect them for easy access, and set them as your device's wallpaper with ease. Enjoy a hassle-free wallpaper customization experience
    fontawesome_icon_name                 : mug-hot


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
